# This file was generated by GoReleaser. DO NOT EDIT.
class DnsHeaven < Formula
  desc "Fixes stupid macOS DNS stack (/etc/resolv.conf)"
  homepage "https://github.com/greenboxal/dns-heaven"
  version "v1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/greenboxal/dns-heaven/releases/download/v1.0.0/dns-heaven_Darwin_x86_64.tar.gz"
    sha256 "727fb2bc6a5a600ff2bd234550af86b4598b9394f75767f25dab79aea9298b02"
  elsif OS.linux?
  end
  
  depends_on "go"

  def install
    bin.install "dns-heaven"
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.greenboxal.dnsheaven</string>
    <key>ProgramArguments</key>
    <array>
        <string>#{bin}/dns-heaven</string>
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>

  EOS
  end
end
